namespace LCollector.Utils
{
    public static class Commands
    {
        public static IReadOnlyList<string> HUAWEI_COMMANDS {get;} =
        [
            "screen-length 0 temporary",
            "display version",
            "display device",
            "display esn",
            "display device pic-status",
            "display health",
            "display cpu usage",
            "display cpu-defend car  information default",
            "display memory",
            "display voltage",
            "display temperature",
            "display elabel brief ",
            "display elabel optical brief",
            "display alarm all",
            "display alarm active",
            "display license ",
            "display paf | i mldp",
            "display startup",
            "display interface",
            "display ip interface brief",
            "display interface brief",
            "display interface description",
            "display optical brief",
            "display arp all",
            "display ospf peer",
            "display ospf peer brief",
            "display ospf interface",
            "display bgp peer",
            "display bgp all summary",
            "display bgp ipv6 peer",
            "display bgp vpnv4 all peer",
            "display bgp vpnv6 all peer",
            "display bgp labeled peer",
            "display bgp vpn-target peer",
            "display bgp l2vpn-ad peer",
            "display bgp evpn peer",
            "display bgp labeled routing-table label",
            "display bgp mdt all peer",
            "display ip routing-table statistics",
            "display mpls lsp statistics",
            "display mpls ldp session",
            "display mpls ldp peer",
            "display mpls ldp interface verbose",
            "display mpls ldp interface",
            "display mpls interface",
            "display bfd session all",
            "display bfd interface",
            "display current"
        ];

        public static IReadOnlyList<string> CISCOXE_COMMANDS {get;} =
        [
            "term leng 0",
            "sh ip arp",
            "sh ip arp vrf GERENCIA",
            "sh ip arp vrf IUB-DADOS",
            "sh ip arp vrf ABIS",
            "sh ip arp vrf S1",
            "sh ip arp vrf VIDEOSURV",
            "sh ip arp vrf ALL_IP_NRI",
            "sh ip arp vrf GERL3_EBT_CLARO",
            "show ethernet event microwave status",
            "sh ver",
            "dir",
            "show ptp clock running domain 0",
            "sh env",
            "sh proc",
            "sh lic",
            "show redundancy",
            "show platform",
            "sh int sum",
            "show module",
            "sh ip pim nei",
            "sh ip ospf nei",
            "show ip ospf interface brief",
            "sh int trans",
            "sh cdp neig",
            "sh inter",
            "sh ip int b",
            "show running-config",
            "show interfaces description",
            "sh inv",
            "sh ip mroute",
            "sh ip route",
            "sh ip bgp all summ",
            "show log",
            "show clock",
            "show cem circuit detail",
            "show policy-map interface",
            "show mpls l2 vc",
            "show ip sla statistics",
            "show standby brief",
            "sh int desc",
            "sh mpls l2 vc",
            "sh xconnect all"
        ];

        public static IReadOnlyList<string> CISCOXR_COMMANDS {get;} =
        [
            "term leng 0",
            "sh arp",
            "sh arp vrf GERENCIA",
            "sh arp vrf IUB-DADOS",
            "sh arp vrf ABIS",
            "sh arp vrf S1",
            "sh arp vrf VIDEOSURV",
            "show arp vrf ALL_IP_SCL",
            "show arp vrf NGN-NET_SCL",
            "show arp vrf GLOBAL_28573_SCL",
            "show arp vrf ALL_IP_SCL",
            "show arp vrf GBIU",
            "show arp vrf IUH",
            "show bgp all all summary",
            "show bgp vrf GERENCIA summary",
            "show bgp vrf IUB-DADOS summary",
            "show bgp vrf ABIS summary",
            "show bgp vrf S1 summary",
            "show bgp vrf VIDEOSURV summary",
            "show bgp vrf EMBRATEL_CORP summary",
            "show bgp vrf CLARO_CORP summary",
            "show bgp vrf NET_CORP summary",
            "show bgp vrf GER-EBT summary",
            "show bgp vrf S1-5G summary",
            "show bgp vrf GBIU summary",
            "show interfaces description",
            "show ospf neighbor",
            "show hsrp brief",
            "show bundle",
            "show platform",
            "sh inventory rack",
            "sh inventory",
            "show ntp associations",
            "show ntp status",
            "show version",
            "show interfaces description",
            "show mpls ldp neighbor",
            "show ipv4 interface brief",
            "show route",
            "show bgp",
            "show ospf neighbor",
            "show bgp all all summary",
            "show bgp vrf all summary",
            "show inventory",
            "show pim neighbor",
            "show interfaces",
            "show policy-map interface all",
            "show mrib route",
            "show clock",
            "show license",
            "show l2vpn bridge-domain group EOMPLS_XCONNECT_EMBRATEL brief",
            "show l2vpn bridge-domain group EOMPLS_XCONNECT_EMBRATEL",
            "show l2vpn bridge-domain group BBIP_EBT",
            "show l2vpn bridge-domain summary",
            "show l2vpn bridge-domain brief",
            "show install inactive summary",
            "show hw-module fpd location all",
            "show ipsla statistics",
            "show install active summary",
            "show install inactive summary",
            "show install committed summary",
            "show hw-module fpd",
            "sh license all",
            "show ospf interface brief",
            "show license platform summary",
            "show call-home smart-licensing statistics",
            "license smart deregister",
            "license smart renew auth",
            "license smart register idtoken ",
            "dir disk0:",
            "dir harddisk:",
            "show log",
            "show hw-module fpd",
            "show controllers optics * summary"
        ];

        public static IReadOnlyList<string> ALCATEL_COMMANDS {get;} =
        [
            "admin display-config",
            "show card",
            "show chassis",
            "show uptime",
            "show version",
            "show users",
            "show time",
            "show card",
            "show mda",
            "show system cpu",
            "show system information",
            "show system memory-pools",
            "show log log-id 100",
            "show chassis environment power-feed ",
            "show chassis environment",
            "show system security authentication",
            "show router interface",
            "show port",
            "show port description",
            "show lag ",
            "show router ospf neighbor",
            "show router ospf neighbor detail",
            "show router ospf interface",
            "show router bgp neighbor",
            "show router bgp summary",
            "show router bgp routes",
            "show router route-table summary",
            "show router route-table",
            "show router mpls lsp",
            "show router ldp session",
            "show router ldp peer",
            "show router ldp interface detail",
            "show router ldp interface",
            "show router bfd session",
            "show router bfd interface",
            "show system ptp ",
            "show system ptp  clock 1 ",
            "show system ptp  clock 2",
            "show system ntp ",
            "show port",
            "show router arp",
            "show service sap-using",
            "show service sdp-using",
            "show router policy"
        ];
    }
}